services:
  - type: web
    name: flexindihair
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: flexindihair-db
          property: connectionString
      - key: NODE_ENV
        value: production
      # Example for adding another environment variable
      - key: API_KEY
        value: "your-api-key-here"  # Replace with actual key if needed

databases:
  - name: flexindihair-db
    plan: free
    ipAllowList: []  # Only allow internal connections

# Optional section if you're using any other services
# You can add additional services like Redis, or other integrations if needed.
# services:
#   - type: redis
#     name: redis-cache
#     plan: free
