services:
  - type: web
    name: flexindihair
    env: node
    buildCommand: npm install && npm run db:push && npm run build
    startCommand: npm start
    plan: starter
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: flexindihair-db
          property: connectionString
      - key: NODE_ENV
        value: production

databases:
  - name: flexindihair-db
    plan: starter
    ipAllowList: [] # only allow internal connections